// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psoqkucpxfvtexzpxrct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzb3FrdWNweGZ2dGV4enB4cmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzA0OTEsImV4cCI6MjA2MDUwNjQ5MX0.86_voeTLn9lUE9I-xLOPCllPAObnL9QFw-UIXgg70ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);